### ISSUE TITLE
non-repeatable builds

### ISSUE THREAD

**Issue by hansfbaier** [kintex-chatter/xc7k325t-blinky-nextpnr#13]
I have the strange issue that on some builds,
the board just does nothing (LEDs tri-stated),
and when I clean and rebuild then on some builds
it works.

**Comment by unbtorsten** [comment]
Are you able to reproduce one of each cases? This would allow for a comparison of binary files. In fact, two subsequently generated bitstreams may not be the same, even if LEDs blink for both images?!

**Comment by hansfbaier** [comment]
This was an issue with openFPGALoader. Lowering its frequency solved it.
